baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[params]
  description = "Chris Keele. Avian photographer. Baker of bread. Bodyweight fitness enthusiast."
  author = "Chris Keele"
  authorImage = "/images/birds/_M6A4570-750px.jpg"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "/svg/home.svg"
  [[menu.main]]
    name = "Images"
    url = "/images/"
    weight = 2
    pre = "/svg/image.svg"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
    pre = "/svg/signal.svg"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "/svg/information.svg"

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/alkaliphile"
    pre = "/svg/github-original.svg"

  [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/chris_keele/"
    pre = "/svg/instagram-original.svg"
