baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[params]
  description = "Chris Keele. Avian photographer. Baker of bread. Practitioner of bodyweight fitness."
  primaryColor = "#1a535c"
  backgroundColor = "#f7f7f7"
  googleFont = "Roboto"
  author = "Chris Keele"
  authorImage = "/images/birds/_M6A4570-750px.jpg"

[menu]
  [[menu.main]]
    name = "Images"
    url = "/images/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/alkaliphile"
  pre = "<img src=\"svg/github-original.svg\" alt=\"View my GitHub profile.\" class=\"icon\">"

[[menu.social]]
  name = "Instagram"
  url = "https://www.instagram.com/chris_keele/"
  pre = "<img src=\"svg/instagram-original.svg\" alt=\"Visit me on Instagram!\">"
