baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"

[params]
  description = "Chris Keele. Avian photographer. Baker of bread. Practitioner of bodyweight fitness."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/alkaliphile"
  pre = "<i class='fab fa-github'></i>"

[[menu.social]]
  name = "Instagram"
  url = "https://www.instagram.com/chris_keele/"
  pre = "<i class='fab fa-instagram'></i>"
