baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"
enableRobotsTXT = true
disablePathToLower = true
summaryLength = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Chris Keele. Bird photographer. Baker of bread. Bodyweight fitness enthusiast."
  author = "Chris Keele"
  authorImage = "/images/birds/_M6A4570-750px.jpg"
  sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    title = "Home section"
    url = "/"
    weight = 1
    pre = "/svg/home-light.svg"
  [[menu.main]]
    name = "Images"
    identifier = "images"
    title = "Images section"
    url = "/images/"
    weight = 2
    pre = "/svg/image-light.svg"
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    title = "Blog section"
    url = "/blog/"
    weight = 3
    pre = "/svg/signal-light.svg"
  [[menu.main]]
    name = "About"
    identifier = "about"
    title = "About section"
    url = "/about/"
    weight = 4
    pre = "/svg/info-light.svg"

  [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/chris_keele/"
    pre = "instagram"
    weight = 1
  [[menu.social]]
    name = "Email"
    url = "mailto:christopher.l.keele@gmail.com"
    pre = "envelope"
    weight = 2
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/alkaliphile"
    pre = "github"
    weight = 3
