baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[params]
  description = "Chris Keele. Avian photographer. Baker of bread. Practitioner of bodyweight fitness."
  author = "Chris Keele"
  authorImage = "/images/birds/_M6A4570-750px.jpg"

[menu]
  [[menu.main]]
    name = "Images"
    url = "/images/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/alkaliphile"
    pre = "/svg/github-original.svg"

  [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/chris_keele/"
    pre = "/svg/instagram-original.svg"
