baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chris Keele'
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[params]
  description = "Chris Keele. Avian photographer. Baker of bread. Practitioner of bodyweight fitness."
  primaryColor = "#1a535c"
  googleFont = "Roboto"
  author = "Chris Keele"
  authorImage = "/images/birds/_M6A4570-750px.jpg"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Images"
    url = "/images/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/alkaliphile"
  pre = "<i class='fab fa-github'></i>"

[[menu.social]]
  name = "Instagram"
  url = "https://www.instagram.com/chris_keele/"
  pre = "<i class='fab fa-instagram'></i>"
